# ####################################################################################
# ######### Config for CorePlugin, only change the values not the structure! #########
# ####################################################################################